In [7]:

import numpy as np
import pandas as pd

In [5]:
number=[10,20,30,40,50]
result=[]
for numbers in number:
    result.append(numbers*2)
print(result)

[20, 40, 60, 80, 100]


In [6]:
numbers=np.array([10,20,30,40,50])
result=numbers*2
print(result)

[ 20  40  60  80 100]


In [8]:
print(type(result))

<class 'numpy.ndarray'>


In [13]:
# arr=np.array([[1,2,3],[4,5,6]])
arr=np.array([[[1,2],[3,4]],[
    [5,6],[7,8]
]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

3
(2, 2, 2)
8
int64


In [26]:
# arr2=np.ones((5,7))
# arr2=np.full(5,7)
# arr2=np.arange(1,11)
# np.arrange(start,stop,step)
arr2=np.arange(0,20,2)
print(arr2)

[ 0  2  4  6  8 10 12 14 16 18]


In [28]:
array1=np.linspace(0,10,5)
print(array1)

[ 0.   2.5  5.   7.5 10. ]


In [32]:
array1=np.random.randint(0,10,5)
print(array1)

[6 5 9 6 5]


In [ ]:
array1=np.array(0,10,5)
print(array1)

In [35]:
array1=np.array([10,20,30,40,50])
print(array1[-1:-4])

[]


In [40]:
array1=np.array([[10,20,30],[40,50,60]])
print(array1[0,1])

20


In [41]:
array1=np.array([10,20,30,40,50])
print(array1[1:4])

[20 30 40]


In [42]:
print(array1[::2])

[10 30 50]


In [45]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array2[:2])
print(array2[:, :2])

[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]
 [7 8]]


In [49]:
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a/b)

[10. 10. 10.]


In [53]:
arr=np.array([10,20,30])
print(arr<15)

[ True False False]


In [60]:
np.sqrt(arr)
np.square(arr)
np.exp(arr)
np.log(arr)
np.sin(arr)
np.cos(arr)

array([-0.83907153,  0.40808206,  0.15425145])

In [61]:
marks=np.array([10,20,30,40,50])
np.sum(marks)

np.int64(150)

In [62]:
np.mean(marks)

np.float64(30.0)

In [64]:
np.std(marks)

np.float64(14.142135623730951)

In [63]:
np.min(marks)

np.int64(10)

In [65]:
np.median(marks)

np.float64(30.0)

In [69]:
marks=np.array([[80,90,70],[60,75,85],[95,88,92]])
np.mean(marks, axis=1)  # Mean of each column

array([80.        , 73.33333333, 91.66666667])

In [70]:
marks=np.array([45,67,89,32,95])
# print(marks>60)

[False False False False False]


In [85]:
result=marks[~((marks>60) & (marks<=90))]
print(result)  # Filter marks greater than 60

[45 32 95]


In [81]:
for mark in marks:
     
        print(mark,mark>=60)

45 False
67 True
89 True
32 False
95 True


In [87]:
arr=np.arange(1,13)
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [88]:
arr=np.array([[1,2],[3,4]])
result=arr.flatten()
print(result)

[1 2 3 4]


In [89]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [90]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
result=np.concatenate((a,b))
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]


In [91]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])
result=np.vstack((a,b))
print(result)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [9 8 7]
 [6 5 4]
 [3 2 1]]


In [93]:
result=np.hstack((a,b))
print(result)

[[1 2 3 9 8 7]
 [4 5 6 6 5 4]
 [7 8 9 3 2 1]]


In [ ]:
array=np.array([10,20,30,40,50,60,70])
result = np.array_split(array, 4)
# print(result)
print(result)

[array([10, 20]), array([30, 40]), array([50, 60]), array([70])]


In [105]:
view=array[1:3]
view[0]=100
print(view)

[100  30]


In [103]:
copy=array[1:3].copy()
print(copy)

[20 30]


In [107]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,5,4],[3,2,1]])

print(a@b)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [108]:
result=np.dot(a,b)
print(result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [112]:
A=np.array([[2,1],[1,3]])
print(np.linalg.det(A))

5.000000000000001
